# Site settings
title: colestock.com
email: james@colestock.com
description: > # this means to ignore newlines until "baseurl:"
  The Internet Home of James Colestock
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.colestock.com" # the base hostname & protocol for your site
twitter_username: JamesColestock
github_username: babalugats76

# Build settings
markdown: kramdown
sass:
    sass_dir: assets/stylesheets
    style: compressed
# Makes pretty (descriptive) permalinks. See Jekyll docs for alternatives.
permalink: pretty
gems: [jekyll-paginate]
paginate_path: "page:num"
# How many articles do you wish to appear on the front page:
paginate: 1    
highlighter: pygments
