title: James Colestock
name: James Colestock
email: james@colestock.com
description: The Internet Home of James Colestock
baseurl: ""
url: "http://www.colestock.com"
markdown: kramdown
sass:
    sass_dir: assets/stylesheets
    style: compressed
permalink: pretty
gems: [jekyll-paginate]
paginate_path: "page/:num"
paginate: 1    
highlighter: pygments
# custom
domain: colestock.com
twitter_username: JamesColestock
github_username: babalugats76
googleplus_username: +JamesColestock
youtube_username: mastertrade
topnposts: 10