# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: James Colestock's Blog
email: james@colestock.com
description: > # this means to ignore newlines until "baseurl:"
  The Official Blog of James Colestock
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.colestock.com" # the base hostname & protocol for your site
twitter_username: JamesColestock
github_username: babalugats76

# Build settings
markdown: kramdown
sass:
    sass_dir: assets/stylesheets
    style: compressed
# Makes pretty (descriptive) permalinks. See Jekyll docs for alternatives.
permalink: pretty

gems: [jekyll-paginate]
paginate_path: "page:num"
# How many articles do you wish to appear on the front page:
paginate: 1    